#%RAML 1.0 Trait

responses:
  400:
    body:
      application/json:
        example:
          {
            "message": "Bad Request",
            "statusCode": "400"
          }
  401:
    body:
      application/json:
        example:
            {
                  "message": "Unauthorized Access",
                  "statusCode": "401"
            }
  404:
    body:
      application/json:
        example:
          {
                  "message": "Resource Not Found",
                  "statusCode": "404"
          }
  415:
    body:
      application/json:
        example:
          {
                  "message": "Invalid Media Type",
                  "statusCode": "415"
          }
  500:
    body:
      application/json:
        example:
          {
                  "message": "Internal Server Error",
                  "statusCode": "500"
          }